package model;

import java.util.Scanner;

public interface Const {

    Scanner scanner = new Scanner(System.in);

    String DATA_FILE_PATH = "data.txt";
    String NO_RESULT = "NO RESULT!";
    String MAKE_CHOICE = "Please make a choice: ";
    String GATHERING_NEW_INFORMATION = "GATHERING NEW INFORMATION!";
    String INVALID_CHOICE = "INVALID CHOICE!";
    String INPUT_MUST_BE_AN_INTEGER = "INPUT MUST BE AN INTEGER!";

    //LOGIN
    String ENTER_YOUR_LOGIN_INFORMATION = "ENTER YOUR LOGIN INFORMATION!";
    String USERNAME = "username: ";
    String PASSWORD = "password: ";
    String LOGGED_IN_AS_ADMINISTRATOR = "LOGGED IN AS ADMINISTRATOR!";
    String LOGGED_IN_AS_MANAGER = "LOGGED IN AS MANAGER!";
    String LOGGED_IN_AS_STAFF = "LOGGED IN AS STAFF!";
    String WRONG_USERNAME_OR_PASSWORD_LOGIN_FAILED = "WRONG USERNAME OR PASSWORD! LOGIN FAILED!";
    String WELCOME = "Welcome, ";

    // PERSONAL INFORMATION
    String ENTER_PERSONAL_ID = "Enter personal ID: ";
    String ENTER_NAME = "Enter name: ";
    String ENTER_DATE_OF_BIRTH = "Enter date of birth: ";

    // GUEST INFORMATION
    String ENTER_DATE_OF_CHECKING_IN = "Enter date of checking in: ";
    String ENTER_DATE_OF_CHECKING_OUT = "Enter date of checking out: ";

    // APARTMENT
    String ENTER_APARTMENT_ID = "Enter apartment ID: ";
    String ENTER_APARTMENT_STATE = "Enter apartment state: ";
    String ENTER_APARTMENT_LEVEL = "Enter apartment level: ";
    String ENTER_APARTMENT_TYPE = "Enter apartment type: ";
    String ENTER_MINIMUM_PRICE = "Enter minimum price: ";
    String ENTER_MAXIMUM_PRICE = "Enter maximum price: ";

    String APARTMENT_ID_EXISTED = "APARTMENT ID IS EXISTED!";
    String APARTMENT_ID_NOT_EXISTED = "APARTMENT ID IS NOT EXISTED!";

    String APARTMENT_LIST_EMPTY = "THE LIST OF APARTMENTS IS EMPTY!";
    String APARTMENT_LIST = "CURRENT LIST OF APARTMENTS:";

    String SEARCH_APARTMENT = "SEARCHING INFORMATION OF AN APARTMENT! APARTMENT'S ID REQUIRED!";
    String SEARCH_APARTMENT_BY_STATE = "SEARCHING APARTMENT BY STATE!";
    String SEARCH_APARTMENT_BY_LEVEL = "SEARCHING APARTMENT BY LEVEL!";
    String SEARCH_APARTMENT_BY_TYPE = "SEARCHING APARTMENT BY TYPE!";
    String SEARCH_APARTMENT_BY_PRICE = "SEARCHING APARTMENT BY PRICE!";

    String ADDING_APARTMENT = "ADDING A NEW APARTMENT!";
    String APARTMENT_ADDED = "APARTMENT INFORMATION ADDED SUCCESSFULLY!";
    String APARTMENT_ADDED_UNSUCCESSFULLY = "APARTMENT INFORMATION ADDED UNSUCCESSFULLY!";
    String UPDATING_APARTMENT = "UPDATING A APARTMENT!";
    String APARTMENT_UPDATED = "APARTMENT INFORMATION UPDATED SUCCESSFULLY!";
    String APARTMENT_UPDATED_UNSUCCESSFULLY = "APARTMENT INFORMATION UPDATED UNSUCCESSFULLY!";
    String DELETING_APARTMENT = "DELETING A APARTMENT!";
    String APARTMENT_DELETED = "APARTMENT INFORMATION DELETED SUCCESSFULLY!";
    String APARTMENT_DELETED_UNSUCCESSFULLY = "APARTMENT INFORMATION DELETED UNSUCCESSFULLY!";

    // STAFF
    String ENTER_STAFF_ID = "Enter apartment ID: ";
    String ENTER_MINIMUM_REVENUE = "Enter minimum revenue: ";
    String ENTER_MAXIMUM_REVENUE = "Enter maximum revenue: ";

    String STAFF_ID_EXISTED = "STAFF ID IS EXISTED!";
    String STAFF_ID_NOT_EXISTED = "STAFF ID IS NOT EXISTED!";

    String STAFF_LIST_EMPTY = "THE LIST OF STAFFS IS EMPTY!";
    String STAFF_LIST = "CURRENT LIST OF STAFFS:";

    String SEARCH_STAFF = "SEARCHING INFORMATION OF AN APARTMENT! STAFF'S ID REQUIRED!";
    String SEARCH_STAFF_BY_REVENUE = "SEARCHING STAFF BY REVENUE!";

    String ADDING_STAFF = "ADDING A NEW STAFF!";
    String STAFF_ADDED = "STAFF INFORMATION ADDED SUCCESSFULLY!";
    String STAFF_ADDED_UNSUCCESSFULLY = "STAFF INFORMATION ADDED UNSUCCESSFULLY!";
    String UPDATING_STAFF = "UPDATING A NEW STAFF!";
    String STAFF_UPDATED = "STAFF INFORMATION UPDATED SUCCESSFULLY!";
    String STAFF_UPDATED_UNSUCCESSFULLY = "STAFF INFORMATION UPDATED UNSUCCESSFULLY!";
    String DELETING_STAFF = "DELETING A STAFF!";
    String STAFF_DELETED = "STAFF INFORMATION DELETED SUCCESSFULLY!";
    String STAFF_DELETED_UNSUCCESSFULLY = "STAFF INFORMATION DELETED UNSUCCESSFULLY!";





    String TURN_BACK = "TURNING BACK TO MAIN MENU!";

}