package model;

import java.util.Scanner;

public interface Const {

    Scanner scanner = new Scanner(System.in);

    String GUEST = "guest";
    String STAFF = "staff";

    String ROOM_DATA_FILE_PATH = "data_room.txt";
    String INVOICE_DATA_FILE_PATH = "data_invoice.txt";
    String GUEST_DATA_FILE_PATH = "data_guest.txt";
    String STAFF_DATA_FILE_PATH = "data_staff.txt";
    String ACCOUNT_DATA_FILE_PATH = "data_account.txt";
    String DATA_EXPORTED_SUCCESSFULLY = "DATA EXPORTED!";
    String DATA_IMPORTED_SUCCESSFULLY = "DATA IMPORTED!";
    String IO_EXCEPTION_DATA_IMPORTED_UNSUCCESSFULLY = "IO EXCEPTION! DATA IMPORTED UNSUCCESSFULLY";
    String IO_EXCEPTION_DATA_EXPORTED_UNSUCCESSFULLY = "IO EXCEPTION! DATA EXPORTED UNSUCCESSFULLY";

    String NO_RESULT = "NO RESULT!";
    String MAKE_CHOICE = "Please make a choice: ";
    String GATHERING_NEW_INFORMATION_FOR_UPDATING = "GATHERING NEW INFORMATION FOR UPDATING!";


    String INVALID_CHOICE = "INVALID CHOICE!";
    String EXCEPTION_ILLEGAL_ARGUMENT = "EXCEPTION: Illegal argument exception!";
    String EXCEPTION_DATE_TIME_PARSE = "EXCEPTION: Date time parse exception!";

    //LOGIN & MENU
    String ENTER_YOUR_LOGIN_INFORMATION = "ENTER YOUR LOGIN INFORMATION!";
    String USERNAME = "username: ";
    String PASSWORD = "password: ";
    String LOGGED_IN_AS = "LOGGED IN AS ";
    String LOGGED_OUT = "LOGGED OUT!";
    String WRONG_USERNAME_OR_PASSWORD_LOGIN_FAILED = "WRONG USERNAME OR PASSWORD! LOGIN FAILED!";
    String TURN_BACK = "TURNING BACK!";

    // PERSONAL INFORMATION
    String ENTER_PERSONAL_ID = "Enter personal ID: ";
    String ENTER_NAME = "Enter name: ";
    String ENTER_DATE_OF_BIRTH = "Enter date of birth (yyyy-mm-dd): ";

    // ROOM
    String ENTER_ROOM_ID = "Enter room ID: ";
    String ENTER_ROOM_STATE = "Enter room state (EMPTY/OCCUPIED): ";
    String ENTER_ROOM_LEVEL = "Enter room level (STANDARD/DELUXE/LUXURY): ";
    String ENTER_ROOM_TYPE = "Enter room type (SINGLE/DOUBLE): ";
    String ENTER_MINIMUM_PRICE = "Enter minimum price: ";
    String ENTER_MAXIMUM_PRICE = "Enter maximum price: ";

    String ROOM_ID_EXISTED = "ROOM ID IS EXISTED!";
    String ROOM_ID_NOT_EXISTED = "ROOM ID IS NOT EXISTED!";
    String ROOM_STATE_NOT_EXISTED = "ROOM STATE IS NOT EXISTED!";
    String ROOM_LEVEL_NOT_EXISTED = "ROOM LEVEL IS NOT EXISTED!";
    String ROOM_TYPE_NOT_EXISTED = "ROOM TYPE IS NOT EXISTED!";

    String ROOM_LIST_EMPTY = "THE LIST OF ROOMS IS EMPTY!";
    String ROOM_LIST = "CURRENT LIST OF ROOMS:";

    String SEARCH_ROOM = "SEARCHING INFORMATION OF AN ROOM! ROOM'S ID REQUIRED!";
    String SEARCH_ROOM_BY_STATE = "SEARCHING ROOM BY STATE!";
    String SEARCH_ROOM_BY_LEVEL = "SEARCHING ROOM BY LEVEL!";
    String SEARCH_ROOM_BY_TYPE = "SEARCHING ROOM BY TYPE!";
    String SEARCH_ROOM_BY_PRICE = "SEARCHING ROOM BY PRICE!";

    String STAFF_INFORMATION_INITIALIZED_UNSUCCESSFULLY = "STAFF INFORMATION INITIALIZED UNSUCCESSFULLY!";
    String INVALID_ROLE = "INVALID ROLE";

    String ROOM_INFORMATION_INITIALIZED_UNSUCCESSFULLY = "ROOM INFORMATION INITIALIZED UNSUCCESSFULLY!";
    String ADDING_ROOM = "ADDING A NEW ROOM!";
    String ROOM_ADDED = "ROOM INFORMATION ADDED!";
    String ROOM_ADDED_UNSUCCESSFULLY = "ROOM INFORMATION ADDED UNSUCCESSFULLY!";
    String UPDATING_ROOM = "UPDATING INFORMATION OF A ROOM!";
    String ROOM_UPDATED = "ROOM INFORMATION UPDATED!";
    String ROOM_UPDATED_UNSUCCESSFULLY = "ROOM INFORMATION UPDATED UNSUCCESSFULLY!";
    String DELETING_ROOM = "DELETING A ROOM!";
    String ROOM_DELETED = "ROOM INFORMATION DELETED!";
    String ROOM_DELETED_UNSUCCESSFULLY = "ROOM INFORMATION DELETED UNSUCCESSFULLY!";

    // STAFF
    String ENTER_STAFF_ID = "Enter staff ID: ";
    String ENTER_STAFF_ROLE = "Enter staff role: ";
    String ENTER_MINIMUM_SALES = "Enter minimum sales: ";
    String ENTER_MAXIMUM_SALES = "Enter maximum sales: ";

    String PERSONAL_ID_EXISTED = "PERSONAL ID EXISTED!";
    String STAFF_ID_EXISTED = "STAFF ID IS EXISTED!";
    String STAFF_ID_NOT_EXISTED = "STAFF ID IS NOT EXISTED!";

    String STAFF_LIST_EMPTY = "THE LIST OF STAFFS IS EMPTY!";
    String STAFF_LIST = "CURRENT LIST OF STAFFS:";

    String SEARCH_STAFF = "SEARCHING INFORMATION OF A STAFF! STAFF'S ID REQUIRED!";
    String SEARCH_STAFF_BY_SALES = "SEARCHING STAFF BY SALES!";

    String ADDING_STAFF = "ADDING A NEW STAFF!";
    String STAFF_ADDED = "STAFF INFORMATION ADDED!";
    String STAFF_ADDED_UNSUCCESSFULLY = "STAFF INFORMATION ADDED UNSUCCESSFULLY!";
    String UPDATING_STAFF = "UPDATING INFORMATION OF A STAFF!";
    String STAFF_UPDATED = "STAFF INFORMATION UPDATED!";
    String STAFF_UPDATED_UNSUCCESSFULLY = "STAFF INFORMATION UPDATED UNSUCCESSFULLY!";
    String DELETING_STAFF = "DELETING INFORMATION OF A STAFF!";
    String STAFF_DELETED = "STAFF INFORMATION DELETED!";
    String STAFF_DELETED_UNSUCCESSFULLY = "STAFF INFORMATION DELETED UNSUCCESSFULLY!";

    // GUEST
    String ENTER_GUEST_ID = "Enter guest's personal ID: ";
    String GUEST_ID_EXISTED = "GUEST ID IS EXISTED!";
    String GUEST_ID_NOT_EXISTED = "GUEST ID IS NOT EXISTED!";
    String GUEST_LIST_EMPTY = "THE LIST OF GUESTS IS EMPTY!";
    String GUEST_LIST = "CURRENT LIST OF GUESTS:";
    String SEARCH_GUEST = "SEARCHING INFORMATION OF A GUEST! GUEST'S ID REQUIRED!";

    // ACCOUNT
    String ENTER_ACCOUNT_ID = "Enter account ID: ";
    String ENTER_ACCOUNT_ROLE = "Enter account role: ";
    String ENTER_ACCOUNT_USERNAME = "Enter account's username: ";
    String ENTER_ACCOUNT_PASSWORD = "Enter account's password: ";

    String ACCOUNT_ID_EXISTED = "ACCOUNT ID IS EXISTED!";
    String ACCOUNT_ID_NOT_EXISTED = "ACCOUNT ID IS NOT EXISTED!";

    String ACCOUNT_LIST_EMPTY = "THE LIST OF ACCOUNTS IS EMPTY!";
    String ACCOUNT_LIST = "CURRENT LIST OF ACCOUNTS:";

    String SEARCH_ACCOUNT = "SEARCHING INFORMATION OF A ACCOUNT! ACCOUNT'S ID REQUIRED!";

    String ACTIVATING_AN_ACCOUNT = "ACTIVATE AN ACCOUNT!";
    String DEACTIVATING_AN_ACCOUNT = "DEACTIVATE AN ACCOUNT!";
    String YOUR_ACCOUNT_HAS_NOT_BEEN_ACTIVATED = "YOUR ACCOUNT HAS NOT BEEN ACTIVATED!";
    String THIS_ACCOUNT_IS_ALREADY_ACTIVATED = "THIS ACCOUNT IS ALREADY ACTIVATED!";
    String THIS_ACCOUNT_IS_ALREADY_DEACTIVATED = "THIS ACCOUNT IS ALREADY DEACTIVATED!";
    String THIS_ACCOUNT_HAS_BEEN_ACTIVATED = "THIS ACCOUNT HAS BEEN ACTIVATED!";
    String THIS_ACCOUNT_HAS_BEEN_DEACTIVATED = "THIS ACCOUNT HAS BEEN DEACTIVATED!";

    // INVOICE
    String ENTER_INVOICE_ID = "Enter invoice ID: ";

    String INVOICE_ID_EXISTED = "INVOICE ID IS EXISTED!";
    String INVOICE_ID_NOT_EXISTED = "INVOICE ID IS NOT EXISTED!";
    String MONTH_NAME_DOES_NOT_EXIST = "MONTH NAME DOES NOT EXIST!";
    String THERE_IS_NO_INVOICE_PAID_IN_THAT_MONTH = "THERE IS NO INVOICE PAID IN THAT MONTH!";
    String TOTAL_SALES = "TOTAL SALES: ";
    String THE_ROOM_HAS_BEEN_OCCUPIED = "THE ROOM HAS BEEN OCCUPIED!";
    String GATHERING_GUEST_INFORMATION = "GATHERING GUEST INFORMATION!";

    String INVOICE_LIST_EMPTY = "THE LIST OF INVOICES IS EMPTY!";
    String INVOICE_LIST = "CURRENT LIST OF INVOICES:";

    String SEARCH_INVOICE = "SEARCHING INFORMATION OF A INVOICE! INVOICE'S ID REQUIRED!";

    String ADDING_INVOICE = "ADDING A NEW INVOICE!";
    String INVOICE_ADDED = "INVOICE INFORMATION ADDED!";
    String INVOICE_ADDED_UNSUCCESSFULLY = "INVOICE INFORMATION ADDED UNSUCCESSFULLY!";
    String UPDATING_INVOICE = "UPDATING INFORMATION OF AN INVOICE!";
    String INVOICE_UPDATED = "INVOICE INFORMATION UPDATED!";
    String INVOICE_UPDATED_UNSUCCESSFULLY = "INVOICE INFORMATION UPDATED UNSUCCESSFULLY!";
    String DELETING_INVOICE = "DELETING INFORMATION OF AN INVOICE!";
    String INVOICE_DELETED = "INVOICE INFORMATION DELETED!";
    String INVOICE_DELETED_UNSUCCESSFULLY = "INVOICE INFORMATION DELETED UNSUCCESSFULLY!";


    String PAYING_AN_INVOICE = "PAYING FOR AN INVOICE!";
    String INVOICE_PAID = "INVOICE PAID!";
    String INVOICE_PAID_UNSUCCESSFULLY = "INVOICE PAID UNSUCCESSFULLY!";
    String LIST_INVOICES_BY_MONTH = "LIST INVOICES BY MONTH!";
    String ENTER_MONTH = "Enter month: ";
}